TARGET = iphone:clang:16.5:16.0

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ResolutionXPrefs
ResolutionXPrefs_FILES = RXRootListController.m
ResolutionXPrefs_FRAMEWORKS = UIKit
ResolutionXPrefs_PRIVATE_FRAMEWORKS = Preferences
ResolutionXPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk
